import { useEffect, useState } from 'react';
import { api } from '../lib/api';
import { useAuth } from '../context/AuthContext';

export default function AdminDashboard() {
  const { session } = useAuth();
  const [employees, setEmployees] = useState([]); const [vendors, setVendors] = useState([]); const [leaves, setLeaves] = useState([]); const [purchases, setPurchases] = useState([]); const [vendor, setVendor] = useState({ name: '', category: '', contact_email: '' }); const [employee, setEmployee] = useState({ full_name: '', email: '', password: '', department: '' }); const [message, setMessage] = useState(''); const [loading, setLoading] = useState(true);
  async function load() { try { const [people, supplierData, leaveData, purchaseData] = await Promise.all([api('/api/hr/employees', session), api('/api/procurement/vendors', session), api('/api/hr/leave-requests', session), api('/api/procurement/purchase-requests', session)]); setEmployees(people); setVendors(supplierData); setLeaves(leaveData); setPurchases(purchaseData); } catch (error) { setMessage(error.message); } finally { setLoading(false); } }
  useEffect(() => { load(); }, [session]);
  async function addVendor(event) { event.preventDefault(); try { await api('/api/procurement/vendors', session, { method: 'POST', body: JSON.stringify(vendor) }); setVendor({ name: '', category: '', contact_email: '' }); setMessage('Vendor added.'); await load(); } catch (error) { setMessage(error.message); } }
  async function addEmployee(event) { event.preventDefault(); try { await api('/api/hr/employees', session, { method: 'POST', body: JSON.stringify(employee) }); setEmployee({ full_name: '', email: '', password: '', department: '' }); setMessage('Employee account created.'); await load(); } catch (error) { setMessage(error.message); } }
  const pending = [...leaves, ...purchases].filter((item) => item.status === 'pending').length;
  return <div className="page"><div className="page-heading"><div><span className="eyebrow">Admin workspace</span><h1>Organization overview</h1><p>One view of your people, requests, and suppliers.</p></div><div className="queue-number"><strong>{pending}</strong><span>pending</span></div></div>{message && <div className="flash">{message}</div>}<div className="metric-row"><div className="metric"><span>People</span><strong>{employees.length}</strong><small>In the directory</small></div><div className="metric"><span>Vendors</span><strong>{vendors.length}</strong><small>Available suppliers</small></div><div className="metric"><span>Total requests</span><strong>{leaves.length + purchases.length}</strong><small>Across all modules</small></div></div><div className="content-grid admin-grid"><section className="panel"><div className="section-heading"><div><span className="eyebrow">Directory</span><h2>Employees</h2></div></div>{loading ? <div className="empty"><span className="loader" />Loading people...</div> : <div className="directory-list">{employees.map((item) => <div className="directory-row" key={item.id}><span className="avatar small">{item.full_name?.[0]}</span><div><strong>{item.full_name}</strong><small>{item.department || 'No department'}</small></div><span className="tag">{item.role}</span></div>)}</div>}</section><section className="panel"><div className="section-heading"><div><span className="eyebrow">Suppliers</span><h2>Vendor directory</h2></div></div><form onSubmit={addVendor}><label>Vendor name<input value={vendor.name} onChange={(event) => setVendor({ ...vendor, name: event.target.value })} required /></label><div className="form-grid"><label>Category<input value={vendor.category} onChange={(event) => setVendor({ ...vendor, category: event.target.value })} /></label><label>Contact email<input type="email" value={vendor.contact_email} onChange={(event) => setVendor({ ...vendor, contact_email: event.target.value })} /></label></div><button className="button button-primary" type="submit">Add vendor <span>↗</span></button></form><div className="directory-list">{vendors.slice(0, 6).map((item) => <div className="directory-row" key={item.id}><div><strong>{item.name}</strong><small>{item.category || 'General supplier'}</small></div></div>)}</div></section></div></div>;
}
