import { useEffect, useState } from 'react';
import { api } from '../lib/api';
import { useAuth } from '../context/AuthContext';

export default function ApprovalsDashboard() {
  const { session, profile } = useAuth();
  const [items, setItems] = useState([]); const [loading, setLoading] = useState(true); const [message, setMessage] = useState(''); const [busy, setBusy] = useState(null);
  async function load() { try { setItems(await api('/api/approvals/pending', session)); } catch (error) { setMessage(error.message); } finally { setLoading(false); } }
  useEffect(() => { load(); }, [session]);
  async function decide(id, decision) { const comment = window.prompt(`Optional comment for this ${decision} decision`) || ''; setBusy(id); try { await api(`/api/approvals/${id}`, session, { method: 'PATCH', body: JSON.stringify({ decision, comment }) }); setMessage(`Request ${decision}.`); await load(); } catch (error) { setMessage(error.message); } finally { setBusy(null); } }
  return <div className="page"><div className="page-heading"><div><span className="eyebrow">{profile.role} workspace</span><h1>Approval queue</h1><p>Review requests carefully, then keep the team moving.</p></div><div className="queue-number"><strong>{items.length}</strong><span>waiting</span></div></div>{message && <div className="flash">{message}</div>}<section className="panel approvals-view"><div className="section-heading"><div><span className="eyebrow">Needs your attention</span><h2>Pending requests</h2></div></div>{loading ? <div className="empty"><span className="loader" />Loading approvals...</div> : items.length === 0 ? <div className="empty">No pending approvals. Your queue is clear.</div> : <div className="approval-table">{items.map((item) => { const leave = item.leave_requests; const purchase = item.purchase_requests; const target = leave || purchase; return <article className="approval-card" key={item.id}><div className="approval-main"><span className="tag">{leave ? 'Leave request' : 'Purchase request'}</span><h3>{target?.profiles?.full_name || 'Team member'}</h3><p>{leave ? `${leave.start_date} to ${leave.end_date} · ${leave.reason || 'No reason provided'}` : `${purchase.item_description} · ₹${purchase.amount}`}</p>{purchase?.vendors?.name && <small>Vendor: {purchase.vendors.name}</small>}</div><div className="approval-actions"><button className="button button-approve" disabled={busy === item.id} onClick={() => decide(item.id, 'approved')}>Approve</button><button className="button button-reject" disabled={busy === item.id} onClick={() => decide(item.id, 'rejected')}>Reject</button></div></article>; })}</div>}</section></div>;
}
